context:
  version: "0.9.1"

package:
  name: pangolin
  version: ${{ version }}

source:
  url: https://github.com/stevenlovegrove/Pangolin/archive/refs/tags/v${{ version }}.tar.gz
  sha256: cc6c5fbd81a9dc40dac220ef57e46d7db0c1deb6d6ae62ba7f685c68c100119f

build:
  number: 1
  script: |
    mkdir build
    cd build
    cmake ${CMAKE_ARGS} -DBUILD_TESTS=OFF -DBUILD_TOOLS=OFF \
          -DCMAKE_CXX_FLAGS="-I${PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/include" \
          -DCMAKE_INSTALL_PREFIX=${PREFIX} \
          -DGLEW_INCLUDE_DIR=${PREFIX}/include \
          -DGLEW_LIBRARY=$PREFIX/lib/libGLEW.so \
          ${SRC_DIR}
    make -j${CPU_COUNT} install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ cdt('mesa-libgl-devel') }}
    - ${{ cdt('mesa-libegl-devel') }}
    - ${{ cdt('libxcb') }}
  host:
    - glew
    - eigen
    - kernel-headers_linux-64
    - wayland
    - libxkbcommon

about:
  homepage: https://github.com/stevenlovegrove/Pangolin
  license: MIT
  license_file: LICENSE
  summary: OpenGL video display / interaction library.
  description: Pangolin is a lightweight portable rapid development library for managing OpenGL display / interaction and abstracting video input.
  documentation: https://github.com/stevenlovegrove/Pangolin
  repository: https://github.com/stevenlovegrove/Pangolin

extra:
  recipe-maintainers:
    - zicklag
