package:
  name: fbow-stella
  version: 0.0.1

source:
  git: https://github.com/stella-cv/FBoW.git
  rev: c925ef9d444c39d2967791b8c08bf3dfda9c4e1c

build:
  number: 1
  script: |
    mkdir build
    cd build
    cmake ${CMAKE_ARGS} -DBUILD_TESTS=OFF \
          -DCMAKE_PREFIX_PATH=${PREFIX} \
          -DCMAKE_INSTALL_PREFIX=${PREFIX} \
          -DCMAKE_SHARED_LINKER_FLAGS="-L${PREFIX}/lib" \
          ${SRC_DIR}
    make -j${CPU_COUNT} install

requirements:
  build:
    - git
    - gxx=11
    - cmake=3.21
    - ${{ cdt('mesa-libgl-devel') }}
  host:
    - eigen=3.4
    - opencv=4.9

about:
  homepage: https://github.com/stella-cv/FBoW
  repository: https://github.com/stella-cv/FBoW
  license: MIT
  license_file: LICENSE
  summary: This is a modified version of the original Fast Bag of Words by @rmsalinas.

extra:
  recipe-maintainers:
    - zicklag
