context:
  version: "2.3.0"

package:
  name: openmvs
  version: ${{ version }}

source:
  url: https://github.com/cdcseacave/openMVS/archive/refs/tags/v${{version}}.tar.gz
  sha256: ac7312fb71dbab18c5b2755ad9ac3caa40ec689f6f369c330ca73c87c1f34258

build:
  number: 1
  script: |
    mkdir make
    cd make
    export LDFLAGS="${LDFLAGS} -Wl,--allow-shlib-undefined"
    cmake ${CMAKE_ARGS} \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH=${PREFIX} \
          -DCMAKE_INSTALL_PREFIX=${PREFIX} \
          ${SRC_DIR}
    make -j${CPU_COUNT} install
    rm ${PREFIX}/bin/OpenMVS/Tests
    mv ${PREFIX}/bin/OpenMVS/* $PREFIX/bin
    rmdir ${PREFIX}/bin/OpenMVS

requirements:
  build:
    - gxx
    - pkg-config
    # - cuda-toolkit # TODO: make CUDA work
    - cmake
    - make
    - ${{ cdt('mesa-libgl-devel') }}
  host:
    - python=3.12
    - eigen>=3.4
    - opencv>=2.4
    - cgal>=4.2
    - boost>=1.56
    - vcglib=2023.12
    - glew
    - glfw
  run:
    - python=3.12
    - ${{ pin_compatible('libboost', exact=True) }}
    - ${{ pin_compatible('libboost-python', exact=True) }}
    - ${{ pin_compatible('libopencv', exact=True) }}

about:
  homepage: http://cdcseacave.github.io/
  repository: https://github.com/cdcseacave/openMVS
  license: AGPL-3.0
  license_file: LICENSE
  summary: Open Multi-View Stereo reconstruction library.

extra:
  recipe-maintainers:
    - zicklag
